/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAaveLike,
  IAaveLikeInterface,
} from "../../../contracts/Router.sol/IAaveLike";

const _abi = [
  {
    inputs: [],
    name: "aUSDT",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "supply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAaveLike__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveLikeInterface {
    return new Interface(_abi) as IAaveLikeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAaveLike {
    return new Contract(address, _abi, runner) as unknown as IAaveLike;
  }
}
