/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockAaveSol from "./MockAave.sol";
export type { mockAaveSol };
import type * as routerSol from "./Router.sol";
export type { routerSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { CourseMarket } from "./CourseMarket";
export type { LENS } from "./LENS";
export type { SimpleAMM } from "./SimpleAMM";
export type { TestERC20 } from "./TestERC20";
