/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface RouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LENS"
      | "USDT"
      | "WETH"
      | "aave"
      | "aggregator"
      | "amm"
      | "depositLensVia1Inch"
      | "depositToAaveFromLENS"
      | "depositToAaveV3FromLENS"
      | "owner"
      | "poolV3"
      | "renounceOwnership"
      | "setAave"
      | "setAggregator"
      | "setAmm"
      | "setPoolV3"
      | "swapEthForLens"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposited" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "LENS", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "aave", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "aggregator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "amm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositLensVia1Inch",
    values: [BigNumberish, BigNumberish, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToAaveFromLENS",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToAaveV3FromLENS",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "poolV3", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAave",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAggregator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setAmm", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setPoolV3",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapEthForLens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "LENS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "aave", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "aggregator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "amm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositLensVia1Inch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToAaveFromLENS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToAaveV3FromLENS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poolV3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAave", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAmm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPoolV3", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapEthForLens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    lensIn: BigNumberish,
    ethOut: BigNumberish,
    usdtOut: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    lensIn: bigint,
    ethOut: bigint,
    usdtOut: bigint
  ];
  export interface OutputObject {
    user: string;
    lensIn: bigint;
    ethOut: bigint;
    usdtOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Router extends BaseContract {
  connect(runner?: ContractRunner | null): Router;
  waitForDeployment(): Promise<this>;

  interface: RouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LENS: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  WETH: TypedContractMethod<[], [string], "view">;

  aave: TypedContractMethod<[], [string], "view">;

  aggregator: TypedContractMethod<[], [string], "view">;

  amm: TypedContractMethod<[], [string], "view">;

  depositLensVia1Inch: TypedContractMethod<
    [
      amountIn: BigNumberish,
      minUsdtOut: BigNumberish,
      usePoolV3: boolean,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  depositToAaveFromLENS: TypedContractMethod<
    [amountIn: BigNumberish, minEthOut: BigNumberish, minUsdtOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositToAaveV3FromLENS: TypedContractMethod<
    [amountIn: BigNumberish, minEthOut: BigNumberish, minUsdtOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poolV3: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAave: TypedContractMethod<[aave_: AddressLike], [void], "nonpayable">;

  setAggregator: TypedContractMethod<[agg_: AddressLike], [void], "nonpayable">;

  setAmm: TypedContractMethod<[amm_: AddressLike], [void], "nonpayable">;

  setPoolV3: TypedContractMethod<[pool_: AddressLike], [void], "nonpayable">;

  swapEthForLens: TypedContractMethod<
    [minOut: BigNumberish],
    [bigint],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LENS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aave"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aggregator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "amm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositLensVia1Inch"
  ): TypedContractMethod<
    [
      amountIn: BigNumberish,
      minUsdtOut: BigNumberish,
      usePoolV3: boolean,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositToAaveFromLENS"
  ): TypedContractMethod<
    [amountIn: BigNumberish, minEthOut: BigNumberish, minUsdtOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositToAaveV3FromLENS"
  ): TypedContractMethod<
    [amountIn: BigNumberish, minEthOut: BigNumberish, minUsdtOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolV3"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAave"
  ): TypedContractMethod<[aave_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAggregator"
  ): TypedContractMethod<[agg_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAmm"
  ): TypedContractMethod<[amm_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolV3"
  ): TypedContractMethod<[pool_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapEthForLens"
  ): TypedContractMethod<[minOut: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,uint256,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
